### ISSUE TITLE
How to disable Fluentify temporarily?

### ISSUE THREAD

**Issue by woosts** [Fluentify-IO/Fluentify#6]
How to disable Fluentify temporarily? Now whenever I select texts, Fluentify will work on it.
But I just want to use it when I really need to, not every time I select texts.

**Comment by TechwizardSD** [comment]
In the top right corner of the pop-up window, there is an "Push Left" icon, click it to triggle.

Of course, in the next version, the automatic pop-up function will be disabled by default.
