### ISSUE TITLE
"Turbo mode" leads to misunderstanding

### ISSUE THREAD

**Issue by woosts** [Fluentify-IO/Fluentify#7]
I misunderstood the "turbo mode" to use the better version of ChatGPT (the 3.5 for plus users), but it is not, it is for popping up the window once you select something.
Maybe we can change a name of the mode to clarify this.

**Comment by TechwizardSD** [comment]
Thank you for bringing this to my attention. I appreciate your feedback and will be sure to make necessary adjustments in the next version to clarify the purpose of the "turbo mode." I will also consider renaming the mode to avoid any confusion in the future. Thanks again!

**Comment by TechwizardSD** [comment]
Meanwhile, in the current version, we use the 3.5-turbo api, which returns results faster than the chatGPT. Additionally, in the next version, we will be employing the stream mode to display information, providing users with an improved experience.

**Comment by lty1993** [comment]
@woosts 

The Turbo Mode feature in Fluentify automatically performs tasks without the need for excessive mouse clicking, making text editing tasks less tedious. 

To start, activate Turbo Mode by clicking on the turbo mode icon. Then, select the operation you wish to perform, such as retouching. With Turbo Mode activated, Fluentify will automatically appear and perform the selected operation on the newly selected text, eliminating the need for an extra mouse click.
