### ISSUE TITLE
I want to a Chrome new tab extension for Fluentify

### ISSUE THREAD

**Issue by felibq** [Fluentify-IO/Fluentify#8]
Your plugin seems very useful, have you considered making a Chrome new tab extension? It can be used when opening a new tab.

**Comment by CocoSgt** [comment]
I am not sure what "a Chrome new tab extension" specifically refers to. Could you provide a detailed user story or give a specific scenario?

**Comment by CocoSgt** [comment]
That sounds like a great idea. I will need to consider how to integrate it with the current plugin's functionality. Thank you very much for your great idea.
